name: Deploy | Inversiones | Infinityfree

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Build
        run: npx astro build
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}

      - name: Subir por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_41868502
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /inversiones.boxwill.com/htdocs/
